/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import dev.rafuru.datastructures.stack.Stack;
public class App {
    public static void main(String[] args) {
        Stack<String> stack = new Stack(String.class);
        System.out.println(stack.getSize());
        stack.push("Rafael");
        stack.push("Carrillo");
        System.out.println(stack.pop());
        System.out.println(stack.pop());

        stack.push("test");

        System.out.println(stack.pop());
        System.out.println(stack.getSize());
    }
}
