/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import dev.rafuru.datastructures.btree.BTree;
public class App {
    public static void main(String[] args) {
       BTree binaryTree = new BTree();
       binaryTree.add(30);
       binaryTree.add(20);
       binaryTree.add(15);
       binaryTree.add(10);
       binaryTree.add(5);
       binaryTree.add(4);
       binaryTree.add(99);
       binaryTree.add(20);
       binaryTree.add(77);
       binaryTree.add(30);
       System.out.println("---------- In Order ----------");
       binaryTree.transverseInOrder(binaryTree.getRoot());
       System.out.println("---------- Pre Order ----------");
       binaryTree.transversePreOrder(binaryTree.getRoot());
       System.out.println("---------- Post Order ----------");
       binaryTree.transversePostOrder(binaryTree.getRoot());

    }
}
