import dev.rafuru.games.Game;
import dev.rafuru.games.N64Game;
import dev.rafuru.games.NSwitchGame;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    static Predicate<Game> isN64Game = g -> g.getPlatform().equals("Nintendo 64");

    public static void main(String[] args) {

        List<Game> gameList = generateGameList();
        gameList
                .stream()
                .filter(isN64Game.and(g -> g.getPlayers()>1))
                .map(g->(N64Game)g)
                .forEach(g-> System.out.printf("%s %b %s%n",g.getTitle(),g.expansionPackRequired,g.getPlayers()));


    }

    private static List<Game> generateGameList(){
        List<Game> gameList = new ArrayList<>();
        gameList.add(new NSwitchGame("Captain Toad",true,1,false));
        gameList.add(new N64Game("Donkey Kong 64",false,4,true));
        gameList.add(new N64Game("Mario Party 64",false,4,true));
        gameList.add(new NSwitchGame("Astral Chain",true,1,false));
        gameList.add(new NSwitchGame("Pokemon Sword",true,1,true));
        gameList.add(new N64Game("Mario Kart 64",true,1,false));
        return gameList;
    }

}
